Repository teamterning/Terning-iOS, pull requests merged in 2024-08, with the labels that each got.

#107 [Fix] #97 - 필터링 재설정 방식을 BottomSheet 모달 방식으로 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomScrapButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Logout/LogoutViewContoller.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: :bug: Fix, 🍀 명진

#108 [Fix] #105 - Sticky Header로 구현할 셀을 통합했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/HomeInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/SortInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
Labels: :bug: Fix, 🐣 민성

#113 [Fix] #112 - sticky header를 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/GradientLayerView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
Labels: ✨ Feat, 🐣 민성

#116 [Fix] #109 - Calendar 일부 레이아웃 변경
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/CALayer+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/CalendarDateHeaderView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeView.swift
Labels: :bug: Fix, 🍀 명진

#117 [Refactor] #115 - 캘린더 MVVM 구조로 전면 수정 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/Service/Calendar/ScrapsService.swift
  Terning-iOS/Terning-iOS/Network/Service/Calendar/TNCalendarService.swift
  Terning-iOS/Terning-iOS/Network/Service/Providers.swift
  Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Resource/Utils/Toast.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/Header/CalendarDateFooterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/Header/CalendarDateHeaderView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/EventView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewModel/TNCalendarViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
  Terning-iOS/Terning-iOS/Source/Repository/ScrapsRepository.swift
  Terning-iOS/Terning-iOS/Source/Repository/TNCalendarRepository.swift
Labels: 🍀 명진, 🔨 Refactor
