Repository teamterning/Terning-iOS, pull requests merged in 2024-07, with the labels that each got.

#9 [Setting] #7 - 폰트/컬러 시스템 세팅 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_blue1.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_green1.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_green2.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_orange.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_orange2.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_pink.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_purple.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_red.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_yellow.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey100.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey150.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey200.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey300.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey350.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey400.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey500.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/sunday_red.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_black.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_green.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/warning_red.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_calendar.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_calendar.imageset/calendar.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_calendar_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_calendar_fill.imageset/calendar-1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_home.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_home.imageset/Vector.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_home_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_home_fill.imageset/Vector-1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_person.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_person.imageset/person.fill.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_person_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_person_fill.imageset/person.fill-1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_search.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_search.imageset/Group.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_search_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/TabBar/ic_search_fill.imageset/Group-1.svg
  Terning-iOS/Terning-iOS/Resource/Constants/.gitkeep
  Terning-iOS/Terning-iOS/Resource/Extension/UILabel+.swift
  Terning-iOS/Terning-iOS/Resource/Extension/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/Fonts/.gitkeep
  Terning-iOS/Terning-iOS/Resource/Fonts/Pretendard-Light.otf
  Terning-iOS/Terning-iOS/Resource/Fonts/Pretendard-Medium.otf
  Terning-iOS/Terning-iOS/Resource/Fonts/Pretendard-Regular.otf
  Terning-iOS/Terning-iOS/Resource/Fonts/Pretendard-SemiBold.otf
  Terning-iOS/Terning-iOS/Resource/Literal/FontLiterals.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: 🍀 명진, :gear: Setting

#17 [Feat] #12 - progress 컴포넌트 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
Labels: ✨ Feat, 🌷 민지

#21 [Feat] #20 - CustomDatePicker, getKrDate 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Extension/Foundation+/Date+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
Labels: ✨ Feat, 🌷 민지

#24 [Feat] #14 - Custom NavigatoinBar를 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobDetailInfoView.swift
Labels: 🍀 명진, ✨ Feat

#23 [Design] #22 - WelcomeViewController UI 작업했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/WelcomView/View/WelcomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/WelcomView/ViewController/WelcomeViewController.swift
Labels: 🎨 Design, 🌷 민지

#28 [Feat] #25 - ProfileViewController 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
  Terning-iOS/Terning-iOS/Resource/Utils/ValidationMessage.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/ViewModel/ProfileViewModel.swift
Labels: ✨ Feat, 🌷 민지

#31 [Design] #15 - 홈화면 UI 작업(CardCell 레이아웃 변경 전)
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_downArrow.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_downArrow.imageset/ic_downArrow.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_filter.imageset/slider.horizontal.3.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_verticalBar.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_verticalBar.imageset/Rectangle 34626938.png
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/DecorationCell/DecorationCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/FilteringCell/FilteringCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilteringHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/SortButtonCell/SortButtonCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Model/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Model/ScrapedAndDeadlineModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: 🎨 Design, 🐣 민성

#32 [Feat] #29 - OnboardingViewController 구현
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_sub2.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/WelcomeView/ViewController/WelcomeViewController.swift
Labels: ✨ Feat, 🌷 민지

#35 [Feat] #8 - 공고 상세 페이지 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/Property 1=default.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap.imageset/ios_ic_28_scrap.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Property 1=active.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_scrap_fill.imageset/Vector 1.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomScrapButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobDetailInfoView.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobSummaryInfoView.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/BottomInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/CompanyInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/DetailInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/MainInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/SummaryInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/JobDetailTableViewHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/SummaryInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
Labels: ✨ Feat, 🌷 민지

#34 [Feat] #33 - 필터링 화면 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey375.colorset/Contents.json
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/FilteringCell/FilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/FilteringCell/FilteringCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilteringHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/SortButtonCell/SortButtonCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortBottomSheet/SortBottomSheetViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortBottomSheet/SortBottomSheetview.swift
Labels: ✨ Feat, 🎨 Design, 🐣 민성

#38 [Design] #36 - LoginViewController UI 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple2.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple3.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao2.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao3.png
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobSummaryInfoView.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/BottomInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/CompanyInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/DetailInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/MainInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/SummaryInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/SummaryInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
Labels: 🎨 Design, 🌷 민지

#41 [Design] #27 - CalendarView 작업 하였습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/ic_backArrow_green.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/ic_backArrow_green.imageset/Union.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/ic_frontArrow_green.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/ic_frontArrow_green.imageset/Union-1.svg
  Terning-iOS/Terning-iOS/Resource/Protocols/ViewModelType.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Resource/Utils/LabelFactory.swift
  Terning-iOS/Terning-iOS/Source/Data/Calendar/ScrapResult.swift
  Terning-iOS/Terning-iOS/Source/Data/Calendar/TodayScrapModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/CalendarDateHeaderView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewModel/TNCalendarViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/ProfileView/ViewModel/ProfileViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: 🍀 명진, 🎨 Design

#40 [Feat] #37 - 필터링 세팅 뷰 선택된 버튼 일괄 전달 작업 완료했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
Labels: ✨ Feat, 🐣 민성

#45 [Fix] #44 - 변경된 커스텀 네비 바 적용하였습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
Labels: :bug: Fix, 🐣 민성

#42 [Feat] #39 - kakao 로그인 구현했습니다.
  .gitignore
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Application/AppDelegate.swift
  Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
Labels: ✨ Feat, 🌷 민지

#51 [Feat] #11 - 서버 API 세팅을 완료 했습니다.
  .gitignore
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Network/Service/AuthInterceptor.swift
  Terning-iOS/Terning-iOS/Network/Service/Providers.swift
  Terning-iOS/Terning-iOS/Network/TargetType/AnnouncementsTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/FiltersTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/HomeTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/SearchTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Resource/Extension/Foundation+/Encodable+.swift
  Terning-iOS/Terning-iOS/Resource/Extension/Foundation+/NetworkLoggerPlugin.swift
  Terning-iOS/Terning-iOS/Resource/Utils/UserDefaultWrapper.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/NewTokenModel.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/SignInResponseModel.swift
Labels: 🍀 명진, ✨ Feat

#52 [Feat] #49 - 스티키 헤더 구현과 셀 분기 처리를 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/gradation_bar.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/gradation_bar.imageset/gradationBarImage.png
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/DecorationCell/DecorationCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/FilteringCell/FilteringCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilteringHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/NonJobCardHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/SortButtonCell/SortButtonCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Model/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Model/ScrapedAndDeadlineModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortBottomSheet/SortBottomSheetViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortBottomSheet/SortBottomSheetview.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: ✨ Feat, ❌ Remove, 🐣 민성

#55 [Hotfix] #54 - 깃 충돌 해결 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/NonJobCardHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
Labels: :bug: Fix, 🍀 명진

#58 [Remove] #57 - 기기에 맞게 레이아웃 재수정과 스크랩 구현 코드 삭제
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/ScrapedAndDeadlineModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/NonScrapInfoCells.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Model/JobCardModel.swift
Labels: ❌ Remove, 🐣 민성

#56 [Feat] #53 - Apple Login 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
  Terning-iOS/Terning-iOS/Terning-iOS.entitlements
Labels: 🍀 명진, ✨ Feat

#67 [Fix] #62 - 스크랩 기능 구현, 카카오 로그인 구현
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Application/AppDelegate.swift
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/SignInResponseModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
Labels: 🍀 명진, ✨ Feat

#68 [Feat] #61 - 프로필 이미지 선택 뷰 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_0.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_0.imageset/profile_0.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_1.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_1.imageset/profile_1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_2.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_2.imageset/profile_2.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_3.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_3.imageset/profile_3.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_4.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_4.imageset/profile_4.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_5.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_5.imageset/profile_5.svg
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/Cell/ProfileImageCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileImageView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileImageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileImageViewModel.swift
Labels: ✨ Feat, 🌷 민지

#65 [Feat] #64 - 오늘 마감인 관심 공고 데이터 바인딩와 마이페이지 구현 그리고 홈화면에서의 자잘한 구현을 처리했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/my_page_vertical_bar.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/my_page_vertical_bar.imageset/my_page_vertical_bar.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/home_logo.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/home_logo.imageset/TerningLogo.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/ScrapedAndDeadlineModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/UserProfileInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/NonJobCardHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: ✨ Feat, ❌ Remove, 🐣 민성

#70 [Feat] #69 - 바텀시트 + 카카오톡 자동 로그인을 구현 하였습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_splash.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_splash.imageset/ios_splash.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomBottmSheetViewController.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/SignInResponseModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileImageView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileImageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
Labels: 🍀 명진, ✨ Feat

#74 [Feat] #71 - 자동 로그인 수정, 캘린더 API 연결
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/NewTokenModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
Labels: :bug: Fix, 🍀 명진, ✨ Feat

#75 [Feat] #73 - 탐색 뷰 구현했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSearchView.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSortButton.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/GraphicCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: ✨ Feat, 🌷 민지

#78 [Feat] #77 - 탐색 뷰 API 연결했습니다.
  Terning-iOS/Terning-iOS/Source/Data/Search/AdvertisementsModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Search/RecommendAnnouncementModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/RecommendCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: ✨ Feat, 🌷 민지

#80 [Feat] #79 - 탐색 결과 뷰 API 연결했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Data/Search/SearchResultModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/JobCardCells/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: 🍀 명진, ✨ Feat

#83 [Feat] #81 - 캘린더 API 연결 하였습니다.
  Terning-iOS/.swiftlint.yml
  Terning-iOS/Terning-iOS/Application/SceneDelegate.swift
  Terning-iOS/Terning-iOS/Network/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Calendar/ScrapModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
Labels: 🍀 명진, ✨ Feat

#84 [Feat] #82 - 공고 상세 페이지 조회 API 연결
  Terning-iOS/Terning-iOS/Network/TargetType/AnnouncementsTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: ✨ Feat, 🌷 민지

#87 [Feat] #85 - 스크랩 함수 추가, 캘린더 색상 변경 문제 해결
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Source/Data/Calendar/ScrapModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
Labels: 🍀 명진, ✨ Feat

#89 [Feat] #72 - 홈화면 API 연결중입니다.
  Terning-iOS/Terning-iOS/Network/TargetType/HomeTargetType.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/ScrapedAndDeadlineModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/UserFilteringInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/UserProfileInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/HeaderCells/FilterHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cells/ScrapInfoCells/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/MainHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
Labels: ✨ Feat, 🐣 민성

#90 [Feat] #88 - 스크랩 삭제 구현
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
Labels: 🍀 명진, ✨ Feat

#98 [Fix] #96 - QA반영(UIPickerView 인덱스 문제)
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_NotAnouncement.imageset/img_NotAnouncement.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_non_deadline.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_non_deadline.imageset/non_deadline.png
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/NonScrapInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
Labels: :bug: Fix, 🐣 민성
