Repository teamterning/Terning-iOS, pull requests merged in 2024-12, with the labels that each got.

#227 [Fix] #168 - 카카오 로그인에서 카카오 앱이 작동 안되는 문제를 해결 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Utils/setImage.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/AuthInterceptor.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Providers.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/AnnouncementsTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/FiltersTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/HomeTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/SearchTargetType.swift
Labels: Fix :bug:, 명진 🍀

#231 [Feat] #230 - 필터링 페이지 기능 추가 (직무 추가) 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_accounting.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_accounting.imageset/ic_accounting.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_all.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_all.imageset/ic_all.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkbox.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkbox.imageset/ios_ic_18_checkbox55.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkbox_fill.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkbox_fill.imageset/ios_ic_18_checkbox.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_design.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_design.imageset/ic_design.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_extra.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_extra.imageset/ic_extra.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_it.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_it.imageset/ic_it.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_marketing.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_marketing.imageset/ic_marketing.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_plan.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_plan.imageset/ic_plan.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_research.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_research.imageset/ic_research.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_sales.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_sales.imageset/ic_sales.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomCheckButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSegmentedControl.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Filters/FiltersService.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/FiltersTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/FiltersRepository.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/FiltersModel.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/Grade.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/JobType.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/WorkingPeriod.swift
  Terning-iOS/Terning-iOS/Source/Domain/RepositoryInterface/FiltersRepositoryInterface.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewModel/FilteringViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/Cell/JobCategoryCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewController/JobFilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewModel/JobFilteringViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewModel/PlanFilteringViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
Labels: Feat ✨, 민지 🌷

#234 [Fix] #233 - 온보딩, 웰컴뷰 디자인 수정했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/Cell/JobCategoryCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/ViewController/WelcomeViewController.swift
Labels: Fix :bug:, Design 🎨, 민지 🌷
