Repository teamterning/Terning-iOS, pull requests merged in 2024-10, with the labels that each got.

#200 [Fix] #197 - 2차 QA를 반영했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
Labels: Fix :bug:, 민성 🐣

#201 [Fix] #199 - 최종 QA 반영 하였습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UserProfileInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/MyPage/MyPageCellModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageBasicViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/SearchCollectionViewHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/ViewController/WelcomeViewController.swift
Labels: Fix :bug:, 명진 🍀, Chore 📎

#204 [Fix] #203 - 온보딩 & 탐색 3차 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
Labels: Fix :bug:, 민지 🌷

#205 [Fix] #196 - 페이지 되돌아왔을때, 해당 인덱스값의 데이터만 reload되게 변경했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: Fix :bug:, 민지 🌷

#206 [Setting] #202 - v1.0.1 업데이트
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Protocols/ProfileViewModelType.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
Labels: 명진 🍀, Setting :gear:

#210 [Feat] #208 - SearchViewController 를 수정 하고, 무한 스크롤 배너를 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSearchBar.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Search/AdvertisementsModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/SearchCollectionViewHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
Labels: 명진 🍀, Feat ✨, Del 🧹

#213 [Fix] #212 - 탐색뷰 배너 변경했습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_1.imageset/ios_ad_1.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_3.imageset/ios_ad_3.png
  Terning-iOS/Terning-iOS/Source/Domain/Model/Search/AdvertisementsModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: Fix :bug:, 민지 🌷

#216 [Feat] #211 - Amplitude 구현 및 세팅
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift
  Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeManager.swift
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/UIView+.swift
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Login/LoginService.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageAccountOptionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarController.swift
Labels: 명진 🍀, Feat ✨, ⌛️ASAP

#218 [Setting] #217 - v1.0.2 버전 배포 했습니다.
  README.md
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/UnavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/AdvertisementCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: 명진 🍀, Setting :gear:, AppStore📱

#220 [Setting] #219 - v1.0.3 버전 배포 했습니다.
  README.md
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_1.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_1.imageset/ios_ad_1.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_1.imageset/ios_ad_2_month9.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_2.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_2.imageset/ios_ad_3.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_3.imageset/Contents.json
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewModel/SearchViewModel.swift
Labels: Setting :gear:, AppStore📱
