Repository teamterning/Terning-iOS, pull requests merged in 2024-09, with the labels that each got.

#121 [Fix] #120 - 캘린더 일부 기능을 수정 하였습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/TNCalendarDateCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
Labels: :bug: Fix, 🍀 명진

#118 [Feat] #114 - 정렬기능 구현
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
Labels: ✨ Feat, 🐣 민성

#122 [Refactor] #119 - 소셜 로그인 MVVM 구조로 전면 수정 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/Service/Login/LoginService.swift
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Source/Data/SignIn/NewTokenModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Splash/SplashViewController.swift
  Terning-iOS/Terning-iOS/Source/Repository/LoginRepository.swift
Labels: 명진 🍀, Refactor 🔨

#124 [Fix] #123 - 픽커뷰 레이아웃을 디자인 명세서에 맞게 수정했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
Labels: Fix :bug:, 민성 🐣

#134 [Fix] #133 - 마이페이지 UI 및 구조 수정했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_profileArrow.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_profileArrow.imageset/ios_ic_20_profile.svg
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Source/Data/MyPage/MyPageCellModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageAccountOptionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageBasicViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageProfileViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/View/MyPageView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: Fix :bug:, 민지 🌷

#132 [Fix] #131 - 곧 마감되는 공고카드의 디자인 및 api 명세서의 변경사항을 반영해주었습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_sub3.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/NonScrapInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/ScrapInfoHeaderCell.swift
Labels: Fix :bug:, 민성 🐣

#138 [Add] #137 - UIButton Configuration 배경색 변경 코드 추가
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
Labels: 명진 🍀, Add 📥

#136 [Fix] #135 - 로그아웃, 탈퇴하기 UI 및 로직 구현, API 연결했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Resource/Protocols/AccountOptionViewModelType.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/UserProfileInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/View/AccountOptionView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewModel/LogoutViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewModel/WithdrawViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Logout/LogoutViewContoller.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageAccountOptionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageProfileViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
Labels: Fix :bug:, 민지 🌷

#143 [Fix] #128 - 로그인 로직을 일부 변경 하였습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Network/Service/Login/LoginService.swift
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/basic.imageset/1_basic.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/basic.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/calenderTerning.imageset/5_calender.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/calenderTerning.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/glass.imageset/4_glass.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/glass.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/lucky.imageset/2_lucky.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/lucky.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/passion.imageset/6_passion.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/passion.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/smart.imageset/3_smart.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/smart.imageset/Contents.json
  Terning-iOS/Terning-iOS/Source/Presentation/Login/ViwController/LoginViewController.swift
Labels: Fix :bug:, 명진 🍀

#145 [Fix] #144 -웰컴 & 온보딩 화면 UI 수정사항 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey50.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
Labels: Fix :bug:, 민지 🌷

#142 [Fix] #141 - 공고 상세 페이지 UI 변경했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_view.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_view.imageset/ios_ic_14_view.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobSummaryInfoView.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/CompanyInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/JobDetailTableViewHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/MainInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/SummaryInfoTableViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
Labels: Fix :bug:, 민지 🌷

#148 [Fix] #147 - 마이페이지 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_notice.imageset/1_notice.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_notice.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_opinion.imageset/2_opinion.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_opinion.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_personal.imageset/4_personal.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_personal.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_service.imageset/3_service.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_service.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_version.imageset/5_version.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/MyPage/ic_version.imageset/Contents.json
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewController/MyPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: Fix :bug:, 민지 🌷

#153 [Fix] #152 - 온보딩 페이지 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomOnboardingButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomProgressView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
Labels: Fix :bug:, 민지 🌷

#155 [Fix] #154 - 프로필 페이지 QA 반영했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkmark_circle.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_checkmark_circle.imageset/ios_ic_12_text_signd.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_exclamationmark_circle.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_exclamationmark_circle.imageset/ios_ic_12_text_sign.svg
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/Lotties/login.json
  Terning-iOS/Terning-iOS/Resource/Utils/ValidationMessage.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: Fix :bug:, 민지 🌷

#140 [Fix] #125 - 탐색뷰 관련 UI 수정 반영했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/RecommendCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/Cell/SearchCollectionViewHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/GraphicCollectionViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
Labels: Fix :bug:, 민지 🌷

#157 [Fix] #156 - 온보딩 DTO 및 그래픽 수정했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Resource/Lotties/afterOnboarding.json
  Terning-iOS/Terning-iOS/Resource/Lotties/beforeOnboarding.json
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/ViewController/OnboardingPageViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
Labels: Fix :bug:, 민지 🌷

#159 [Fix] #158 - 공고 상세, 검색 결과 DTO 수정 및 탐색뷰 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSearchView.swift
  Terning-iOS/Terning-iOS/Source/Data/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Data/Search/SearchResultModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: Fix :bug:, 민지 🌷

#150 [Fix] #139 - 홈화면 QA 반영
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/TargetType/FiltersTargetType.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/grey_shadow.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Data/Home/UserFilteringInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/Cell/NonScrapInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
Labels: Fix :bug:, 민성 🐣

#160 [Refactor] #127 - 커스텀 알람 창 전면 수정 하였습니다.
  Terning-iOS/.swiftlint.yml
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Network/Service/Calendar/ScrapsService.swift
  Terning-iOS/Terning-iOS/Network/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_blue.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_blue1.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_green.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_green1.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_orange.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_orange2.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/cal_yellow.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/ViewController+.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/Cell/PaletteCell.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/JobDetailInfoView.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Presentation/AccountOption/ViewController/AccountOptionViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewModel/TNCalendarViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/Cell/MyPageProfileViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/NewHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Repository/ScrapsRepository.swift
Labels: 명진 🍀, Refactor 🔨

#163 [Refactor] #162 - 캘린더 스크랩 수정 및 삭제를 전면 수정하고, 알람창 일부를 변경 했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/ScrapsService.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/TNCalendarService.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/ScrapsRepository.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/TNCalendarRepository.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
Labels: Fix :bug:, 명진 🍀, Refactor 🔨

#165 [Feat] #164 - Lottie 애니메이션 추가
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Lotties/scrapCancel.json
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 명진 🍀, Feat ✨, Add 📥

#167 [Test] #166 - 테스트 객체 및, 캘린더에 스크랩 수를 표시하는 Label을 추가 하였습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/ScrapsRepository.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/TNCalendarRepository.swift
  Terning-iOS/Terning-iOS/Source/Domain/RepositoryInterface/TNCalendarRepositoryInterface.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/Header/CalendarDateFooterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewModel/TNCalendarViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
  Terning-iOS/Terning-iOS/Tests/MockSevices/MockCalendarService.swift
Labels: 명진 🍀, Test ✅, Add 📥

#173 [Fix] #170 - 공고 상세 페이지, 검색결과 페이지 스크랩 기능 수정했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomScrapButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Calendar/AnnouncementModel.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Search/SearchResultModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardScrapedCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: Fix :bug:, 민지 🌷

#175 [Fix] #174 - 로그인, 공고상세 스와이프, 탭바 가벼운 문제들을 해결 하였습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: 명진 🍀, Add 📥, Chore 📎

#178 [Refactor] #177 - 공고상세, 검색결과 모듈 Repository 수정
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Calendar/ScrapsService.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/JobDetailRepository.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/TNCalendarRepository.swift
  Terning-iOS/Terning-iOS/Source/Domain/RepositoryInterface/JobDetailRepositoryInterface.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: 명진 🍀, Refactor 🔨

#171 [Fix] #169 - 변경사항 반영과 의존성 문제 해결
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UpcomingCard.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: Fix :bug:, 민성 🐣

#180 [Add] #179 - JobListingCell 에 그림자를 추가 하였습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
Labels: 명진 🍀, Add 📥

#183 [Fix] #176 - 탐색 뷰 광고 배너 이미지 변경 및 url 이동 로직 추가했습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_2.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_2.imageset/ios_ad_2.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_ad_2.imageset/ios_ad_2_month9.png
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/ViewController/SearchViewController.swift
Labels: Fix :bug:, 민지 🌷

#184 [Fix] #182 - Lottie 변경 및 일부 세팅을 변경 하였습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcodeproj/xcshareddata/xcschemes/Terning-iOS.xcscheme
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Lotties/scrapCancel.json
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/fastlane/Fastfile
  Terning-iOS/fastlane/Matchfile
Labels: Fix :bug:, 명진 🍀, Setting :gear:

#185 [Feat] #172 - 스크랩 기능 구현하였습니다.
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/JobCardModel.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UpcomingCard.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: Feat ✨, 민성 🐣

#187 [Fix] #186 - 2차 QA 반영 하였습니다.
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_NonCardViewInfo.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_NonCardViewInfo.imageset/imgNoCardView.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_NonCardViewInfo.imageset/img_NonCardViewInfo.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_apple_button.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_apple_button.imageset/ios_btn_box_apple.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple2.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_apple.imageset/ios_btn_box_apple3.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao2.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_btn_box_kakao.imageset/ios_btn_box_kakao3.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_kakao_button.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/ios_kakao_button.imageset/ios_btn_box_kakao.svg
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomNavigationBar.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/EmptyView.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/Header/CalendarDateHeaderView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/Cell/JobListingCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/CalendarDateCellView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/InavailableFilterView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Profile/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: Fix :bug:, 명진 🍀

#190 [Fix] #188 - 탐색 뷰 2차 QA 반영했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Lotties/login.json
  Terning-iOS/Terning-iOS/Resource/Lotties/loginAnimation.json
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Search/View/SearchView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/View/SearchResultView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: Fix :bug:, 민지 🌷

#195 [Fix] #192 - 탐색뷰 스크랩 오류 수정했습니다.
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: Fix :bug:, 민지 🌷

#194 [Remove] #193 - 필요없는 코드, assets, 파일을 제거 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_backArrow_green.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_backArrow_green.imageset/Union.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_bag.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_bag.imageset/ic_bag.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_frontArrow_green.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Icons/ic_frontArrow_green.imageset/Union-1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_apple_button.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_apple_button.imageset/ios_btn_box_apple.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_kakao_button.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_kakao_button.imageset/ios_btn_box_kakao.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_login.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_login.imageset/ios_login.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_mypage.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_mypage.imageset/img_mypage.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_scrap_cancel.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_scrap_cancel.imageset/ios_scrap_cancle 1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_search.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/img_search.imageset/ios_search.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/imgwelcomTh1ngjin.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Images/imgwelcomTh1ngjin.imageset/Image.png
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/basic.imageset/1_basic.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/basic.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/calenderTerning.imageset/5_calender.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/calenderTerning.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/glass.imageset/4_glass.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/glass.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/lucky.imageset/2_lucky.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/lucky.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/passion.imageset/6_passion.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/passion.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_0.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_0.imageset/profile_0.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_1.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_1.imageset/profile_1.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_2.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_2.imageset/profile_2.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_3.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_3.imageset/profile_3.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_4.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_4.imageset/profile_4.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_5.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/profile_5.imageset/profile_5.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/smart.imageset/3_smart.svg
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Profile/smart.imageset/Contents.json
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/NewCustomAlertVC.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Login/View/LoginView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/ViewController/SearchResultViewController.swift
Labels: Fix :bug:, 명진 🍀, Del 🧹, Chore 📎, Remove ❌
