Repository teamterning/Terning-iOS, pull requests merged in 2025-01, with the labels that each got.

#237 [Fix] #236 - 필터링뷰 레이아웃 경고 수정
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
Labels: Fix :bug:, 민지 🌷

#239 [Feat] #238 - JobCardCell 마감공고 UI 디자인 변경
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/JobCardCell.swift
Labels: Fix :bug:, 민지 🌷

#241 [Fix] #240 - 필터링뷰 초기화 시 전달된 데이터 기반 UserFilteringData 업데이트 방식으로 수정했습니다.
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/Grade.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/JobType.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Filter/WorkingPeriod.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Home/UserFilteringInfoModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
Labels: Fix :bug:, 민지 🌷

#242 [Refactor] #235 - 홈 화면 전면 수정 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/EmptyView.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Home/HomeService.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/TargetType/HomeTargetType.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/HomeRepository.swift
  Terning-iOS/Terning-iOS/Source/Data/Repository/ScrapRepository.swift
  Terning-iOS/Terning-iOS/Source/Domain/UseCase/HomeUseCase.swift
  Terning-iOS/Terning-iOS/Source/Domain/UseCase/ScrapUseCase.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/View/TNCalendarView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/CheckDeadlineCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/ClosingJobAnnouncementCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/StickyHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/MainSortButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/ViewModel/HomeViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: 명진 🍀, Refactor 🔨, Feat ✨

#244 [Feat] #243 - 홈화면과 필터링을 연결 합니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: 명진 🍀, Feat ✨

#246 [Fix] #245 - 온보딩 & 탐색뷰 3차 스프린트 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomDatePicker.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SearchResult/Cell/SortHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/View/WelcomeView.swift
Labels: Fix :bug:, 민지 🌷

#248 [Fix] #247 - 3차 스프린트 1차 QA 반영 했습니다.
  Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/Login/LoginService.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/User/UserManager.swift
  Terning-iOS/Terning-iOS/Source/Domain/Model/Announcements/JobDetailModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/Cell/StickyHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/MainSortButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/SortSetting/SortSettingViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
Labels: Fix :bug:, 명진 🍀, Calendar📅

#250 [Fix] #249 -필터링 재설정화면 3차 스프린트 1차 QA 반영했습니다.
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomSegmentedControl.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewController/JobFilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/JobFiltering/ViewModel/JobFilteringViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/FilteringSetting/PlanFiltering/ViewModel/PlanFilteringViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/RefactorHome/NewHomeViewController.swift
Labels: Fix :bug:, 민지 🌷

#251 [Setting] #221 - 불필요한 코드를 제거하고, v1.1.0 버전 배포 완료 했습니다.
  README.md
  Terning-iOS/.swiftlint.yml
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomBottmSheetViewController.swift
  Terning-iOS/Terning-iOS/Resource/Utils/CompositionalLayout.swift
  Terning-iOS/Terning-iOS/Source/Data/Network/Service/AuthInterceptor.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/ClosingJobAnnouncementCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/FilterInfoCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/HomeTopCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/IsScrapInfoViewCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/NonJobCardCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/ScrapInfoHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/StickyHeaderCell.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/View/GradientLayerView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/View/HomeView.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/View/MainFilterButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/View/MainSortButton.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/ViewController/HomeViewController.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Home/ViewModel/HomeViewModel.swift
  Terning-iOS/Terning-iOS/Source/Presentation/TabBar/TNTabBarItem.swift
  Terning-iOS/Terning-iOS/Source/Presentation/Welcome/ViewController/WelcomeViewController.swift
Labels: 명진 🍀, Del 🧹, Remove ❌, AppStore📱
