Repository teamterning/Terning-iOS, pull requests merged in 2025-02, with the labels that each got.

#253 [Fix] #252 - 홈 화면 개수가 1000개가 넘어갈 시 문구 변경 | v1.1.1 버전 업데이트
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Source/Presentation/Home/Cell/StickyHeaderCell.swift
Labels: Fix :bug:, 명진 🍀, Setting :gear:

#256 [Fix] #254 - 공고 상세에서 복사 붙여넣기 기능이 되게 수정 했습니다. | v1.1.2 버전 업데이트
  README.md
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Resource/Extension/UIKit+/UITextView+.swift
  Terning-iOS/Terning-iOS/Resource/Utils/TextViewFactory.swift
  Terning-iOS/Terning-iOS/Source/Presentation/JobDetail/Cell/DetailInfoTableViewCell.swift
Labels: Fix :bug:, 명진 🍀

#260 [Feat] #259 - CustomButton 새로 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Presentation/AccountOption/View/AccountOptionView.swift
  Terning-iOS/Terning-iOS/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Home/View/HomeView.swift
  Terning-iOS/Terning-iOS/Presentation/JobDetail/View/JobDetailView.swift
  Terning-iOS/Terning-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Terning-iOS/Terning-iOS/Presentation/Profile/View/ProfileView.swift
  Terning-iOS/Terning-iOS/Presentation/Welcome/View/WelcomeView.swift
  Terning-iOS/Terning-iOS/Resource/Assets.xcassets/Colors/terning_sub1.colorset/Contents.json
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomAlertViewController.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/CustomButton.swift
  Terning-iOS/Terning-iOS/Resource/UIComponents/TerningCustomButton.swift
Labels: 명진 🍀, Feat ✨

#263 [Add] #262 - amplitude 추적 이벤트 추가했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilterButton.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilteringSettingView.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilteringSettingViewController.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilteringView/ViewController/FilteringViewController.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/FilteringView/ViewModel/FilteringViewModel.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/JobFiltering/ViewController/JobFilteringViewController.swift
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/PlanFiltering/ViewController/PlanFilteringViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Profile/ViewController/ProfileViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Welcome/ViewController/WelcomeViewController.swift
  Terning-iOS/Terning-iOS/Resource/Amplitude/AmplitudeEventType.swift
Labels: 명진 🍀, Add 📥, 민지 🌷
