Repository teamterning/Terning-iOS, pull requests merged in 2025-03, with the labels that each got.

#265 [Setting] #264 - Data레이어, Service 폴더 구조를 변경 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Data/Network/Base/Providers.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/AnnouncementsTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/CalendarTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/FiltersTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/HomeTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/MyPageTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/ScrapsTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/SearchTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/FiltersService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/HomeService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/LoginService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/ScrapsService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/TNCalendarService.swift
  Terning-iOS/Terning-iOS/Data/Network/User/AuthInterceptor.swift
Labels: 명진 🍀, Setting :gear:

#268 [Fix] #267 - 직무 카테고리 테두리 Color를 변경 했습니다.
  Terning-iOS/Terning-iOS/Presentation/FilteringSetting/JobFiltering/Cell/JobCategoryCell.swift
Labels: Fix :bug:

#269 [Refactor] #266 - Scrap Feature 레이어 분리
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Data/Network/Base/TargetType/AuthTargetType.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/ScrapsService.swift
  Terning-iOS/Terning-iOS/Data/Repositories/JobDetailRepository.swift
  Terning-iOS/Terning-iOS/Data/Repositories/ScrapRepository.swift
  Terning-iOS/Terning-iOS/Domain/RepositoryInterfaces/ScrapRepositoryInterface.swift
  Terning-iOS/Terning-iOS/Domain/UseCases/ScrapUseCase.swift
  Terning-iOS/Terning-iOS/Presentation/Calendar/ViewController/TNCalendarViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Home/ViewController/HomeViewController.swift
  Terning-iOS/Terning-iOS/Presentation/Home/ViewModel/HomeViewModel.swift
  Terning-iOS/Terning-iOS/Presentation/JobDetail/ViewModel/JobDetailViewModel.swift
  Terning-iOS/Terning-iOS/Presentation/Search/ViewController/SearchViewController.swift
  Terning-iOS/Terning-iOS/Presentation/SearchResult/ViewController/SearchResultViewController.swift
  Terning-iOS/Terning-iOS/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
  Terning-iOS/Terning-iOS/SwiftUI/Views/MainHomeView.swift
Labels: 명진 🍀, Setting :gear:

#270 [Feat] #261 - firebase Push Notification 을 구현 했습니다.
  .gitignore
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Terning-iOS/Terning-iOS/Application/AppDelegate.swift
  Terning-iOS/Terning-iOS/Info.plist
  Terning-iOS/Terning-iOS/Terning-iOS.entitlements
Labels: 명진 🍀, Feat ✨

#272 [Feat] #271 - 서비스 레이어 추가했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Data/Network/Services/AnnouncementsService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/MypageService.swift
  Terning-iOS/Terning-iOS/Data/Network/Services/SearchService.swift
Labels: Feat ✨, 민지 🌷

#282 [Feat] #281 - 강제업데이트 다이얼로그 UI 구현 했습니다.
  Terning-iOS/Terning-iOS.xcodeproj/project.pbxproj
  Terning-iOS/Terning-iOS/Resource/UIComponents/UpdateAlertViewController.swift
Labels: 명진 🍀, Feat ✨

#285 [Fix] #283 - 홈 버튼 Pressed 상태 추가
  Terning-iOS/Terning-iOS/Presentation/Home/Cell/StickyHeaderCell.swift
  Terning-iOS/Terning-iOS/Presentation/Home/View/MainFilterButton.swift
  Terning-iOS/Terning-iOS/Presentation/Home/View/MainSortButton.swift
Labels: Fix :bug:, 명진 🍀
